### PR TITLE
Tabbed screen

### PR DESCRIPTION
**Pull request by ohitsdaniel**
[//]: # (Link the resolved Github issue.)
Helps with #19.

## Problem
[//]: # (Explain why this pull request is necessary.)
To enable Tab bar supports, we need to refactor all Navigation path mutations. 

- [x] path
- [x] lastOccurenceOf(screen) -> ScreenID

- [x] goTo(id:)
- [x] goTo(screen:)

- [x] go(to newPath: [AnyScreen], on: id)
- [x] go(to newPath: [AnyScreen], on: id)

- [x] goBack(to: id)
- [x] goBack(to: screen)

- [x] replacePath

- [x] dismiss(id)
- [x] dismiss(screen)

- [x] dismissSuccessorOf(id)
- [x] dismissSuccessorOf(screen)

- [x] replaceContent(of: id)
- [x] replaceContent(of: screen)

- [x] setActive(id)
- [x] setActive(screen)
 
- [x] didAppear(id)

- [x] View layer for native tab bar

- [x] initialiseDefaultContents(for screenID:, contents)

- [ ] check onDismiss and see if adjustments are needed

- [ ] add tab bar to example app, write UI tests

- [ ]  pushing content onto the tab view
   
## Solution
[//]: # (Explain how you solved the problem.)
Do it. And write tests for it, to make sure nothing breaks. 🚀

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
@ohitsdaniel any updates, maybe you need help with something?

**Comment by ohitsdaniel** [comment]
@krzysztofzablocki I had some time off and tried not to look at code last week. Getting back to this today (just opened up my laptop). Feel free to pick up any of the path mutations and PR into this branch from your fork. Just leave a comment in this PR so that I know what you're working on. 

I will implement lastOccurenceOf now, as it opens up the door for screen-based navigation. :)

**Comment by krzysztofzablocki** [comment]
I'm wrapping my sprint work today and will chat with my team so that I can spend some time and try helping out tomorrow

**Comment by ohitsdaniel** [comment]
Cool, thanks in advance!

**Comment by ohitsdaniel** [comment]
Implemented lastOccurrence(of:) and the screen-based navigation (which for now still calls through to the old linear path mutations. But once we implemented those, they will be ready to go as well.

As I'm still off work and want some time to do code-unrelated activities, I will pick up some more path mutations tomorrow. :)

FYI: Replace path will be the hardest one as we need to define how to replace a tree given a linear path. Would recommend goTo(path:, on:) or goBack(to:) as 'beginner friendly mutations'.

**Comment by ohitsdaniel** [comment]
Picking up dismiss and dismissSuccessor.

**Comment by ohitsdaniel** [comment]
Both dismisses done, next up tomorrow: `go(to newPath: [AnyScreen], on: ScreenID)`, then `goBack(to: ScreenID)`, `replaceContent` and ultimately the goliath, replacePath.

**Comment by ohitsdaniel** [comment]
goBack was easy, as it was a duplicate of `dismissSuccessor`. 🙈

**Comment by ohitsdaniel** [comment]
Finally broke the knot in my head trying to figure how to implement replace / goToPath. All exiting tests pass now, will add tests for tab screens tomorrow evening.

**Comment by mltbnz** [comment]
👀

**Pull request closed without merging**
